server:
  port: 8080
spring:
  application:
    name: "backend"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://certhakzu:mongoPrueba123@cluster0-prueba.kuwmb.mongodb.net/super_heroes_cards?retryWrites=true&w=majority"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
